### ISSUE TITLE
Implement rule not to allow add / edit task without description.

### ISSUE THREAD

**Issue by tgmarinho** [CodeFTW/future-web#31]
Change the implementation to not allow add/editing task without description.

**Comment by rafaspol** [comment]
Humm.

Question: is the list of tasks specific to a purpose or is it generic?

Example of generic use: use the to-do list as a shopping list.

If it is specific for something (that I not know now), ignore what is below.

If it is generic, maybe a better solution is just not displaying the description of the tasks that does not have one (decreasing the space in the list occupied by a task without description).

Because when only the name of the task is enough for the user to know what it is, sometimes he ends up filling anything if the description is mandatory.

**Comment by tgmarinho** [comment]
Description is the name of task, not details of task.
today I can add new **task** with **description**: barbecue with mates codeftw and
**details**: could be itens of ingredients like: coke, meal, salt, etc.

Yes, your suggestion is for compoment Task (list task), my suggestion is for AddTask.js (add task)

**Comment by rafaspol** [comment]
Oh, sorry. I got confused.

You're right.

**Comment by denihs** [comment]
I resolved this, now just need to the Filipe accept the pull request
